version: 2
updates:
  # ============================================================================
  # Docker Image Updates
  # ============================================================================
  - package-ecosystem: "docker"
    directory: "/compose"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      # Group monitoring stack updates together
      monitoring:
        patterns:
          - "prom/prometheus"
          - "grafana/grafana"
          - "grafana/loki"
          - "grafana/promtail"
          - "prom/alertmanager"
          - "prom/node-exporter"
          - "jaegertracing/jaeger"
      # Group security services together
      security:
        patterns:
          - "crowdsecurity/*"
          - "thomseddon/traefik-forward-auth"
      # Group infrastructure services together
      infrastructure:
        patterns:
          - "traefik"
          - "postgres"
          - "redis"
          - "linuxserver/*"
      # Group management tools together
      management:
        patterns:
          - "portainer/portainer-ce"
          - "gethomepage/homepage"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # Socket proxy uses latest by design
      - dependency-name: "tecnativa/docker-socket-proxy"
      # Critical services - only patch/minor updates
      - dependency-name: "crowdsecurity/crowdsec"
        update-types: ["version-update:semver-major"]
      - dependency-name: "traefik"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]

  # ============================================================================
  # GitHub Actions Updates
  # ============================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5