networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_DEFAULT_SUBNET}
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: ${SOCKET_PROXY_SUBNET}
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: ${TRAEFIK_PROXY_SUBNET}
  database:
    name: database
    driver: bridge
    ipam:
      config:
        - subnet: ${DATABASE_SUBNET}
  monitoring:
    name: monitoring
    driver: bridge
    ipam:
      config:
        - subnet: ${MONITORING_SUBNET}
  cache:
    name: cache
    driver: bridge
    ipam:
      config:
        - subnet: ${CACHE_SUBNET}
  backup:
    name: backup
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKUP_SUBNET}

secrets:
  # OAuth secrets
  oauth_client_secret:
    file: ${SECRETSDIR}/oauth_client_secret
  oauth_cookie_secret:
    file: ${SECRETSDIR}/oauth_cookie_secret
  traefik_forward_oauth:
    file: ${SECRETSDIR}/traefik_forward_oauth

  # Database secrets
  postgres_password:
    file: ${SECRETSDIR}/postgres_password
  redis_password:
    file: ${SECRETSDIR}/redis_password
  redis_ratelimit_password:
    file: ${SECRETSDIR}/redis_ratelimit_password
  redis_oauth_password:
    file: ${SECRETSDIR}/redis_oauth_password
  redis_exporter_password:
    file: ${SECRETSDIR}/redis_exporter_password

  # CrowdSec secrets
  crowdsec_lapi_key:
    file: ${SECRETSDIR}/crowdsec_lapi_key
  crowdsec_bouncer_key:
    file: ${SECRETSDIR}/crowdsec_bouncer_key

  # Monitoring secrets
  grafana_admin_password:
    file: ${SECRETSDIR}/grafana_admin_password
  alertmanager_gmail_password:
    file: ${SECRETSDIR}/alertmanager_gmail_password

  # Authentik secrets (optional)
  authentik_secret_key:
    file: ${SECRETSDIR}/authentik_secret_key
  authentik_postgres_password:
    file: ${SECRETSDIR}/authentik_postgres_password
  authentik_api_token:
    file: ${SECRETSDIR}/authentik_api_token

  # Service secrets
  portainer_secret:
    file: ${SECRETSDIR}/portainer_secret

configs:
  # Traefik configs
  traefik_yml:
    file: ${CONFIGDIR}/traefik/traefik.yml
  traefik_middlewares_oauth:
    file: ${CONFIGDIR}/traefik/rules/middlewares-oauth.yml
  traefik_middlewares_cache:
    file: ${CONFIGDIR}/traefik/rules/middlewares-cache.yml
  traefik_middlewares_compress:
    file: ${CONFIGDIR}/traefik/rules/middlewares-compress.yml
  traefik_middlewares_cors:
    file: ${CONFIGDIR}/traefik/rules/middlewares-cors.yml
  traefik_middlewares_rate_limit:
    file: ${CONFIGDIR}/traefik/rules/middlewares-rate-limit.yml
  traefik_middlewares_secure_headers:
    file: ${CONFIGDIR}/traefik/rules/middlewares-secure-headers.yml
  traefik_middlewares_crowdsec_plugin:
    file: ${CONFIGDIR}/traefik/rules/middlewares-crowdsec-plugin.yml
  traefik_chain_api:
    file: ${CONFIGDIR}/traefik/rules/chain-api.yml
  traefik_chain_oauth:
    file: ${CONFIGDIR}/traefik/rules/chain-oauth.yml
  traefik_chain_no_oauth:
    file: ${CONFIGDIR}/traefik/rules/chain-no-oauth.yml
  traefik_chain_public:
    file: ${CONFIGDIR}/traefik/rules/chain-public.yml
  traefik_chain_strict:
    file: ${CONFIGDIR}/traefik/rules/chain-strict.yml
  traefik_tls_opts:
    file: ${CONFIGDIR}/traefik/rules/tls-opts.yml
  traefik_middlewares_errors:
    file: ${CONFIGDIR}/traefik/rules/middlewares-errors.yml

  # Prometheus configs
  prometheus_yml:
    file: ${CONFIGDIR}/prometheus/config/prometheus.yml

  # Loki configs
  loki_config:
    file: ${CONFIGDIR}/loki/loki-config.yml

  # Promtail configs
  promtail_config:
    file: ${CONFIGDIR}/loki/promtail-config.yml

  # Grafana configs
  grafana_ini:
    file: ${CONFIGDIR}/grafana/grafana.ini
  grafana_datasources:
    file: ${CONFIGDIR}/grafana/provisioning/datasources/all.yml
  grafana_dashboards:
    file: ${CONFIGDIR}/grafana/provisioning/dashboards/default.yml

  # AlertManager configs
  alertmanager_yml:
    file: ${CONFIGDIR}/alertmanager/alertmanager.yml
  alertmanager_template:
    file: ${CONFIGDIR}/alertmanager/templates/default.tmpl

  # CrowdSec configs
  crowdsec_config:
    file: ${CONFIGDIR}/crowdsec/config/config.yaml.local
  crowdsec_acquis:
    file: ${CONFIGDIR}/crowdsec/acquis.d/docker-logs.yaml

  # PostgreSQL configs
  postgres_conf:
    file: ${CONFIGDIR}/postgres/postgresql.conf
  postgres_hba:
    file: ${CONFIGDIR}/postgres/pg_hba.conf
  postgres_init:
    file: ${CONFIGDIR}/postgres/init/00-create-databases.sh

  # Redis configs
  redis_conf:
    file: ${CONFIGDIR}/redis/redis.conf
  # NOTE: redis_acl removed - ACL file is generated dynamically by init-acl.sh from Docker secrets
  # See compose/redis.yml entrypoint and config/redis/scripts/init-acl.sh for implementation

  # OAuth2-Proxy configs
  oauth2_proxy_cfg:
    file: ${CONFIGDIR}/oauth2-proxy/oauth2-proxy.cfg

include:
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/error-pages.yml
  - compose/postgres.yml
  - compose/redis.yml

  # SECURITY & AUTHENTICATION
  - compose/oauth.yml # Default: Google OAuth
  # - compose/authentik.yml      # Alternative: Self-hosted Authentik
  - compose/crowdsec.yml

  # MONITORING
  - compose/node-exporter.yml
  - compose/blackbox-exporter.yml
  - compose/prometheus.yml
  - compose/loki.yml
  - compose/promtail.yml
  - compose/alertmanager.yml
  - compose/grafana.yml
  - compose/jaeger.yml

  # APPS
  - compose/portainer.yml
  - compose/vscode.yml
  - compose/homepage.yml
