networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_DEFAULT_SUBNET}
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: ${SOCKET_PROXY_SUBNET}
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: ${TRAEFIK_PROXY_SUBNET}
  database:
    name: database
    driver: bridge
  monitoring:
    name: monitoring
    driver: bridge
  cache:
    name: cache
    driver: bridge
  backup:
    name: backup
    driver: bridge

secrets:
  traefik_forward_oauth:
    file: ${DOCKERDIR}/secrets/traefik_forward_oauth

configs:
  # Traefik configs
  traefik_yml:
    file: ${DATADIR}/traefik/traefik.yml
  traefik_middlewares_oauth:
    file: ${DATADIR}/traefik/rules/middlewares-oauth.yml
  traefik_middlewares_cache:
    file: ${DATADIR}/traefik/rules/middlewares-cache.yml
  traefik_middlewares_compress:
    file: ${DATADIR}/traefik/rules/middlewares-compress.yml
  traefik_middlewares_cors:
    file: ${DATADIR}/traefik/rules/middlewares-cors.yml
  traefik_middlewares_rate_limit:
    file: ${DATADIR}/traefik/rules/middlewares-rate-limit.yml
  traefik_middlewares_secure_headers:
    file: ${DATADIR}/traefik/rules/middlewares-secure-headers.yml
  traefik_chain_api:
    file: ${DATADIR}/traefik/rules/chain-api.yml
  traefik_chain_oauth:
    file: ${DATADIR}/traefik/rules/chain-oauth.yml
  traefik_chain_no_oauth:
    file: ${DATADIR}/traefik/rules/chain-no-oauth.yml
  traefik_chain_public:
    file: ${DATADIR}/traefik/rules/chain-public.yml
  traefik_chain_strict:
    file: ${DATADIR}/traefik/rules/chain-strict.yml
  traefik_tls_opts:
    file: ${DATADIR}/traefik/rules/tls-opts.yml

  # Prometheus configs
  prometheus_yml:
    file: ${DATADIR}/prometheus/config/prometheus.yml

  # Loki configs
  loki_config:
    file: ${DATADIR}/loki/loki-config.yml

  # Promtail configs
  promtail_config:
    file: ${DATADIR}/loki/promtail-config.yml

  # Grafana configs
  grafana_ini:
    file: ${DATADIR}/grafana/grafana.ini
  grafana_datasources:
    file: ${DATADIR}/grafana/provisioning/datasources/all.yml
  grafana_dashboards:
    file: ${DATADIR}/grafana/provisioning/dashboards/default.yml

  # AlertManager configs
  alertmanager_yml:
    file: ${DATADIR}/alertmanager/alertmanager.yml
  alertmanager_template:
    file: ${DATADIR}/alertmanager/templates/default.tmpl

  # CrowdSec configs
  crowdsec_config:
    file: ${DATADIR}/crowdsec/config/config.yaml.local
  crowdsec_acquis:
    file: ${DATADIR}/crowdsec/acquis.d/docker-logs.yaml

  # PostgreSQL configs
  postgres_conf:
    file: ${DATADIR}/postgres/postgresql.conf
  postgres_hba:
    file: ${DATADIR}/postgres/pg_hba.conf
  postgres_init:
    file: ${DATADIR}/postgres/init/00-create-databases.sh

  # Redis configs
  redis_conf:
    file: ${DATADIR}/redis/redis.conf
  redis_acl:
    file: ${DATADIR}/redis/users.acl

  # OAuth2-Proxy configs
  oauth2_proxy_cfg:
    file: ${DATADIR}/oauth2-proxy/oauth2-proxy.cfg

include:
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/postgres.yml
  - compose/redis.yml

  # SECURITY & AUTHENTICATION
  - compose/oauth.yml            # Default: Google OAuth
  # - compose/authentik.yml      # Alternative: Self-hosted Authentik
  - compose/crowdsec.yml
  - compose/traefik-bouncer.yml

  # MONITORING
  - compose/node-exporter.yml
  - compose/prometheus.yml
  - compose/loki.yml
  - compose/promtail.yml
  - compose/alertmanager.yml
  - compose/grafana.yml
  - compose/jaeger.yml

  # APPS
  - compose/portainer.yml
  - compose/vscode.yml
  - compose/homepage.yml
