version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik

  postgres:
    image: postgres:15
    container_name: postgres

  redis:
    image: redis:7
    container_name: redis

  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec

networks:
  default:
    name: jacker_network
  traefik_proxy:
    name: traefik_proxy
