version: "3.9"

networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: $SOCKET_PROXY_SUBNET
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: $TRAEFIK_PROXY_SUBNET

secrets:
  traefik_forward_oauth:
    file: $DOCKERDIR/secrets/traefik_forward_oauth


include:
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml

  # SECURITY
  - compose/oauth.yml
  - compose/crowdsec.yml
  - compose/traefik-bouncer.yml

  # MONITORING
  - compose/node-exporter.yml
  - compose/prometheus.yml
  - compose/grafana.yml

  # APPS
  - compose/portainer.yml
  - compose/vscode.yml
