# Alertmanager Basic Configuration
# https://prometheus.io/docs/alerting/latest/configuration/

global:
  resolve_timeout: 5m

# Templates for alerts
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route
route:
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service', 'severity']

  # Initial wait before sending grouped alerts
  group_wait: 30s

  # Wait before sending new alerts for a group
  group_interval: 5m

  # Wait before resending alerts
  repeat_interval: 12h

  # Default receiver
  receiver: 'default'

  # Child routes
  routes:
    # Null receiver for specific alerts to ignore
    - match:
        alertname: Watchdog
      receiver: 'null'

# Receivers configuration
receivers:
  # Default receiver - logs only (no external notifications until configured)
  - name: 'default'

  # Null receiver - silences alerts
  - name: 'null'

# ====================================================================
# NOTE: SMTP and other notification configs commented out
# ====================================================================
# To enable email notifications, see alertmanager.yml.enhanced.bak for full config
# After configuration, replace this file with the enhanced version and update
# environment variables in .env file.
