---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Jacker
headerStyle: clean
language: es

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Frontend Apps:
    style: row
    columns: 5

  Reverse Proxy:
    style: row
    columns: 5

  Middleware:
    style: row
    columns: 5

  Backend:
    style: row
    columns: 5
