---
# Jacker Homepage Information Widgets - Clean Design
# https://gethomepage.dev/latest/configs/widgets

# Logo
- logo:
    icon: /images/yo_y_jacar.png

# System Resources - Combined CPU & RAM
- resources:
    label: System
    cpu: true
    memory: true

# System Resources - Storage
- resources:
    label: Storage
    disk:
      - /

# Date and Time
- datetime:
    text_size: 2xl
    locale: es
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
