services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "$CROWDSEC_API_PORT:8080"
    networks:
      - traefik_proxy
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/nginx crowdsecurity/discord-crawler-whitelist crowdsecurity/sshd crowdsecurity/wordpress"
      GID: "${GID-1000}"
      TZ: $TZ
      CUSTOM_HOSTNAME: $HOSTNAME
    volumes:
      - /var/log:/var/log:ro
      - $DOCKERDIR/logs:/logs/server:ro
      - $DATADIR/crowdsec/data:/var/lib/crowdsec/data
      - $DATADIR/crowdsec/config:/etc/crowdsec
