services:
  # CrowdSec - Open-source & collaborative security IPS
  # https://community.e.foundation/t/securing-your-self-hosted-using-crowdsec/40039
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec

    security_opt:
      - no-new-privileges:true
      
    restart: unless-stopped

    depends_on: 
      mariadb: 
        condition: service_healthy
      socket-proxy:
        condition: service_healthy

    ports:
      - "127.0.0.1:$CROWDSEC_API_PORT:8080"

    networks:
      - traefik_proxy
      - socket_proxy

    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/nginx crowdsecurity/discord-crawler-whitelist crowdsecurity/sshd crowdsecurity/wordpress"
      GID: "${GID-1000}"
      TZ: $TZ
      DOCKER_HOST: tcp://socket-proxy:2375
      CUSTOM_HOSTNAME: $HOSTNAME
      BOUNCER_KEY_traefik-bouncer: $CROWDSEC_TRAEFIK_BOUNCER_API_KEY
      BOUNCER_KEY_iptable-bouncer: $CROWDSEC_IPTABLES_BOUNCER_API_KEY

    volumes:
      - /var/log:/var/log:ro
      - $DOCKERDIR/logs:/logs/server:ro
      - $DATADIR/crowdsec/data:/var/lib/crowdsec/data
      - $DATADIR/crowdsec/config:/etc/crowdsec
