services:
  # CrowdSec - Open-source & collaborative security IPS
  # https://community.e.foundation/t/securing-your-self-hosted-using-crowdsec/40039
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.0
    container_name: crowdsec

    security_opt:
      - no-new-privileges:true
      
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      socket-proxy:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "cscli", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    ports:
      - "127.0.0.1:$CROWDSEC_API_PORT:8080"

    networks:
      - traefik_proxy
      - socket_proxy

    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/nginx crowdsecurity/discord-crawler-whitelist crowdsecurity/sshd crowdsecurity/wordpress"
      GID: "${PGID-1000}"
      TZ: $TZ
      DOCKER_HOST: tcp://socket-proxy:2375
      CUSTOM_HOSTNAME: $HOSTNAME
      BOUNCER_KEY_traefik-bouncer: $CROWDSEC_TRAEFIK_BOUNCER_API_KEY
      BOUNCER_KEY_iptable-bouncer: $CROWDSEC_IPTABLES_BOUNCER_API_KEY

    volumes:
      - /var/log:/var/log:ro
      - $DOCKERDIR/logs:/logs/server:ro
      - $DATADIR/crowdsec/data:/var/lib/crowdsec/data
      - $DATADIR/crowdsec/config:/etc/crowdsec

    labels:
      # Homepage Integration
      - "homepage.group=Backend"
      - "homepage.name=Crowdsec"
      - "homepage.icon=crowdsec.svg"
      - "homepage.description=Open-Source Threat Intelligence Collaborative"
      - "homepage.widget.type=crowdsec"
      - "homepage.widget.url=http://crowdsec:8080"
      - "homepage.widget.username=$HOSTNAME"
      - "homepage.widget.password=$CROWDSEC_API_LOCAL_PASSWORD"
