services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.5.0
    container_name: homepage
    depends_on:
      socket-proxy:
        condition: service_healthy
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
          pids: 200
        reservations:
          cpus: "0.1"
          memory: 64M
          pids: 200

    networks:
      - traefik_proxy
      - socket_proxy
    volumes:
      - ${CONFIGDIR}/homepage/config:/app/config
      - ${CONFIGDIR}/homepage/images:/app/public/images
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: $PUBLIC_FQDN
    labels:
      - "traefik.enable=true"

      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$PUBLIC_FQDN`)"

      # TLS Configuration
      - "traefik.http.routers.homepage-rtr.tls=true"
      - "traefik.http.routers.homepage-rtr.tls.certresolver=http"
      - "traefik.http.routers.homepage-rtr.tls.options=tls-opts@file"

      # Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth@file"

      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
