services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.5.0
    container_name: homepage
    depends_on:
      socket-proxy:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - traefik_proxy
      - socket_proxy
    volumes:
      - ../data/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$PUBLIC_FQDN`)"
      # Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"