services:
  # Jaeger - Distributed Tracing Platform
  # OPTIONAL: Enable this service only if TRAEFIK_TRACING_ENABLED=true
  # Jaeger provides distributed tracing to monitor and troubleshoot microservices
  #
  # PERMISSION FIX: If you get "mkdir /badger/key: permission denied" error:
  # Solution 1 (Quick): Run: ./scripts/fix-jaeger-permissions.sh
  # Solution 2 (Best): Use tmpfs for ephemeral storage (see tmpfs section below)
  #
  # Persistent vs Ephemeral Storage:
  # - Persistent (current): Traces survive container restarts, requires volume permissions
  # - Ephemeral (tmpfs): Faster, no permission issues, traces cleared on restart (recommended)
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger

    security_opt:
      - no-new-privileges=true

    # Run as specific user to match data directory ownership
    user: "${PUID:-1000}:${PGID:-1000}"

    # Capability restrictions
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:14269/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - traefik_proxy

    # Jaeger Ports:
    # 5775/udp   - accept zipkin.thrift over compact thrift protocol (deprecated)
    # 6831/udp   - accept jaeger.thrift over compact thrift protocol
    # 6832/udp   - accept jaeger.thrift over binary thrift protocol
    # 5778/tcp   - serve configs
    # 16686/tcp  - serve frontend (Jaeger UI)
    # 14268/tcp  - accept jaeger.thrift directly from clients
    # 14250/tcp  - accept model.proto
    # 14269/tcp  - health check
    # 4317/tcp   - OTLP gRPC receiver
    # 4318/tcp   - OTLP HTTP receiver

    # Only expose collector and agent ports internally
    # UI will be exposed through Traefik
    expose:
      - "5778"   # Config server
      - "6831"   # Jaeger agent (thrift compact)
      - "6832"   # Jaeger agent (thrift binary)
      - "14250"  # gRPC
      - "14268"  # HTTP collector
      - "14269"  # Health check
      - "4317"   # OTLP gRPC
      - "4318"   # OTLP HTTP
      - "16686"  # Jaeger UI

    environment:
      # Collector settings
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

      # Storage settings
      - SPAN_STORAGE_TYPE=badger  # Use embedded database (badger)
      # Alternative: use memory (ephemeral, for testing only)
      # - SPAN_STORAGE_TYPE=memory

      # Badger storage configuration
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key

      # Sampling configuration
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json

      # Query settings
      - QUERY_BASE_PATH=/

      # Log level
      - LOG_LEVEL=info

      # Timezone
      - TZ=$TZ

    volumes:
      # Persistent storage for traces
      - $DATADIR/jaeger/badger:/badger
      # Temporary files
      - $DATADIR/jaeger/tmp:/tmp
      # Sampling configuration
      - $CONFIGDIR/jaeger/sampling_strategies.json:/etc/jaeger/sampling_strategies.json:ro

    # Use tmpfs for ephemeral badger storage (RECOMMENDED for better performance)
    # Uncomment below and comment out the /badger volume above if you don't need persistent traces
    # tmpfs:
    #   - /badger:rw,size=2g,uid=1000,gid=1000,mode=1777

    labels:
      - "traefik.enable=true"

      # Jaeger UI Router
      - "traefik.http.routers.jaeger-rtr.entrypoints=websecure"
      - "traefik.http.routers.jaeger-rtr.rule=Host(`jaeger.$PUBLIC_FQDN`)"

      # TLS Configuration
      - "traefik.http.routers.jaeger-rtr.tls=true"
      - "traefik.http.routers.jaeger-rtr.tls.certresolver=http"
      - "traefik.http.routers.jaeger-rtr.tls.options=tls-opts@file"

      # Middleware
      - "traefik.http.routers.jaeger-rtr.middlewares=chain-oauth@file"

      # Jaeger UI Service
      - "traefik.http.routers.jaeger-rtr.service=jaeger-svc"
      - "traefik.http.services.jaeger-svc.loadbalancer.server.port=16686"

      # Homepage Integration
      - "homepage.group=Monitoring"
      - "homepage.name=Jaeger Tracing"
      - "homepage.icon=jaeger.svg"
      - "homepage.href=https://jaeger.$PUBLIC_FQDN"
      - "homepage.description=Distributed Tracing"
