services:
  # Loki - Log aggregation system
  loki:
    image: grafana/loki:3.5.5
    container_name: loki

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    networks:
      - traefik_proxy

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    ports:
      - "127.0.0.1:3100:3100"

    volumes:
      - $DATADIR/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - $DATADIR/loki/data:/loki

    command: -config.file=/etc/loki/loki-config.yml

    environment:
      TZ: $TZ

    labels:
      # Homepage Integration
      - "homepage.group=Backend"
      - "homepage.name=Loki"
      - "homepage.icon=loki.svg"
      - "homepage.description=Log Aggregation System"
      - "homepage.href=https://grafana.$PUBLIC_FQDN/explore"
