services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    
    restart: unless-stopped

    networks:
      - traefik_proxy

    security_opt:
      - no-new-privileges:true

    volumes:
      - $DATADIR/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

    healthcheck:
      retries: 10
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      timeout: 20s

    labels:
      # Homepage Integration
      - homepage.group=Backend
      - homepage.name=MariaDB
      - homepage.icon=mariadb.svg
      - homepage.description=Open-Source Relational Database
