services:
  # Node Exporter - Metrics to Prometheus
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs|rootfs/var/lib/docker/plugins)($$|/)"

    labels:
      # Homepage Integration
      - "homepage.group=Backend"
      - "homepage.name=Node Exporter"
      - "homepage.description=Exporter for hardware and OS metrics"
      - "homepage.href=https://grafana.$PUBLIC_FQDN/d/rYdddlPWk/node-exporter-full"
