services:
  # OAuth2 Proxy - Modern OAuth 2.0 authentication proxy with enhanced security
  # https://oauth2-proxy.github.io/oauth2-proxy/
  oauth:
    container_name: oauth
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    command:
      - --config=/etc/oauth2-proxy/oauth2-proxy.cfg

    security_opt:
      - no-new-privileges=true

    restart: unless-stopped

    # Healthcheck disabled - OAuth2-Proxy uses distroless image with no shell/wget/curl
    # Traefik loadbalancer healthcheck is used instead (see labels below)

    networks:
      - traefik_proxy
      - cache

    depends_on:
      traefik:
        condition: service_healthy
      redis:
        condition: service_healthy

    # ====================================================================
    # SECRETS
    # ====================================================================
    secrets:
      - oauth_client_secret
      - oauth_cookie_secret
      - redis_oauth_password

    configs:
      - source: oauth2_proxy_cfg
        target: /etc/oauth2-proxy/oauth2-proxy.cfg
        mode: "0444"

    volumes:
      # Custom templates (sign_in.html, error.html, robots.txt)
      - ${CONFIGDIR}/oauth2-proxy/templates:/templates:ro

    environment:
      # OAuth Provider Configuration
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=https://oauth.${PUBLIC_FQDN}/oauth2/callback

      # Cookie secret directly from environment variable (Docker secret file caching issue)
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH_COOKIE_SECRET}

      # Redis connection with authentication
      # Password directly in URL (base64 password from environment variable)
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://oauth_user:${REDIS_OAUTH_PASSWORD}@redis:6379/0

      # Email domain whitelist (use * for all domains)
      - OAUTH2_PROXY_EMAIL_DOMAINS=${OAUTH_EMAIL_DOMAINS:-*}

      # Cookie domain and security settings (override config file)
      - OAUTH2_PROXY_COOKIE_DOMAINS=.${PUBLIC_FQDN}
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${PUBLIC_FQDN},.${PUBLIC_FQDN}
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=false
      - OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=15m
      - OAUTH2_PROXY_COOKIE_EXPIRE=${OAUTH_COOKIE_LIFETIME:-604800}s
      - OAUTH2_PROXY_COOKIE_REFRESH=${OAUTH_COOKIE_REFRESH:-3600}s

      # Reverse proxy configuration (CRITICAL for Traefik integration)
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true

      # Custom templates
      - OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR=/templates

      # Logging configuration
      - OAUTH2_PROXY_STANDARD_LOGGING=true
      - OAUTH2_PROXY_REQUEST_LOGGING=true
      - OAUTH2_PROXY_AUTH_LOGGING=true

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # Logging labels for Promtail
      - "logging.component=oauth"
      - "logging.service=authentication"

      # ============================================================
      # ROUTER 1: OAuth Subdomain (oauth.${PUBLIC_FQDN})
      # ============================================================
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.${PUBLIC_FQDN}`)"
      - "traefik.http.routers.oauth-rtr.priority=10"

      # TLS Configuration
      - "traefik.http.routers.oauth-rtr.tls=true"
      - "traefik.http.routers.oauth-rtr.tls.certresolver=http"
#       - "traefik.http.routers.oauth-rtr.tls.options=tls-opts@file"

      # Middlewares - No OAuth required for the OAuth service itself
      - "traefik.http.routers.oauth-rtr.middlewares=chain-no-oauth@file"

      # Service
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"

      # ============================================================
      # ROUTER 2: OAuth Paths on All Domains (for forward auth)
      # ============================================================
      # This router catches /oauth2/* paths on ANY domain and routes to OAuth
      # Needed for forward authentication flow from protected services
      - "traefik.http.routers.oauth-paths-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-paths-rtr.rule=PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth-paths-rtr.priority=100"

      # TLS Configuration
      - "traefik.http.routers.oauth-paths-rtr.tls=true"
      - "traefik.http.routers.oauth-paths-rtr.tls.certresolver=http"
#       - "traefik.http.routers.oauth-paths-rtr.tls.options=tls-opts@file"

      # Middlewares - No OAuth required for the OAuth service itself
      - "traefik.http.routers.oauth-paths-rtr.middlewares=chain-no-oauth@file"

      # Service (same service as main router)
      - "traefik.http.routers.oauth-paths-rtr.service=oauth-svc"

      # ============================================================
      # SERVICE CONFIGURATION
      # ============================================================
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4180"

      # Health check
      - "traefik.http.services.oauth-svc.loadbalancer.healthcheck.path=/ping"
      - "traefik.http.services.oauth-svc.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.oauth-svc.loadbalancer.healthcheck.timeout=5s"

      # Homepage Integration
      - "homepage.group=Security"
      - "homepage.name=OAuth2 Proxy"
      - "homepage.description=Modern OAuth 2.0 Authentication"
      - "homepage.icon=mdi-lock"
      - "homepage.href=https://oauth.${PUBLIC_FQDN}"
      - "homepage.widget.type=generic"
      - "homepage.widget.url=http://oauth:4180/ping"
      - "homepage.widget.label=Status"

    # Healthcheck disabled - OAuth2-Proxy uses distroless image with no shell/wget/curl
    # Traefik loadbalancer healthcheck is used instead (see labels above)

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
