services:
  # Google OAuth - Single Sign On using OAuth 2.0
  # https://www.smarthomebeginner.com/google-oauth-with-traefik-docker/
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    networks:
      - traefik_proxy

    depends_on:
      traefik:
        condition: service_healthy

    environment:
      - CONFIG=/config
      - COOKIE_DOMAIN=$PUBLIC_FQDN
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$PUBLIC_FQDN
      - URL_PATH=/_oauth
      - LOG_LEVEL=warn
      - LOG_FORMAT=text
      - LIFETIME=$OAUTH_COOKIE_LIFETIME
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google

    secrets:
      - source: traefik_forward_oauth
        target: /config

    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.$PUBLIC_FQDN`)"
      - "traefik.http.routers.oauth-rtr.tls.certResolver=http"
      # Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-no-oauth@file"
      # HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"


      # Homepage Integration
      - "homepage.group=Middleware"
      - "homepage.name=OAuth Bouncer"
      - "homepage.description=Google OAuth Traefik Bouncer"
