services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.2
    security_opt:
      - no-new-privileges=true

    # Run as non-root user
    # EXCEPTION: Portainer MUST run as root to:
    # 1. Create BoltDB database at /data/portainer.db
    # 2. Manage Docker resources via socket-proxy
    # 3. Initialize data directory with correct permissions
    # Security is enforced via: cap_drop/cap_add, socket-proxy restrictions, OAuth
    user: "0:0"

    # Capability restrictions
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

    restart: unless-stopped

    # Healthcheck disabled - Portainer uses minimal image without wget/curl
    # Traefik will route based on container running status

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
          pids: 200
        reservations:
          cpus: "0.25"
          memory: 128M
    depends_on:
      socket-proxy:
        condition: service_healthy
      traefik:
        condition: service_healthy

    networks:
      - traefik_proxy
      - socket_proxy

    command: -H tcp://socket-proxy:2375
    volumes:
      - $DATADIR/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      # Traefik configuration
      - "traefik.enable=true"

      # HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$PUBLIC_FQDN`)"

      # TLS Configuration
      - "traefik.http.routers.portainer-rtr.tls=true"
      - "traefik.http.routers.portainer-rtr.tls.certresolver=http"
      - "traefik.http.routers.portainer-rtr.tls.options=tls-opts@file"

      # Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"

      # HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"

      # Homepage Integration
      - "homepage.group=Frontend Apps"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.svg"
      - "homepage.href=https://portainer.$PUBLIC_FQDN"
      - "homepage.description=WebUI for Docker Containers"
