services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.2
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

    depends_on:
      socket-proxy:
        condition: service_healthy
      traefik:
        condition: service_healthy

    networks:
      - traefik_proxy
      - socket_proxy

    command: -H tcp://socket-proxy:2375
    volumes:
      - $DATADIR/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      # Traefik configuration
      - "traefik.enable=true"

      # HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$PUBLIC_FQDN`)"

      # TLS Configuration
      - "traefik.http.routers.portainer-rtr.tls=true"
      - "traefik.http.routers.portainer-rtr.tls.certresolver=http"
#       - "traefik.http.routers.portainer-rtr.tls.options=tls-opts@file"

      # Middlewares
      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"

      # HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"

      # Homepage Integration
      - "homepage.group=Frontend Apps"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.svg"
      - "homepage.href=https://portainer.$PUBLIC_FQDN"
      - "homepage.description=WebUI for Docker Containers"
