services:
  # Promtail - Log shipper for Loki
  promtail:
    image: grafana/promtail:3.5.5
    container_name: promtail

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    depends_on:
      - loki

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - traefik_proxy

    volumes:
      - $DATADIR/loki/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - $DOCKERDIR/logs:/logs:ro
      - promtail-positions:/tmp

    command: -config.file=/etc/promtail/promtail-config.yml

    environment:
      TZ: $TZ
      HOSTNAME: $HOSTNAME

    labels:
      # Homepage Integration
      - "homepage.group=Backend"
      - "homepage.name=Promtail"
      - "homepage.icon=promtail.svg"
      - "homepage.description=Log Shipper for Loki"

volumes:
  promtail-positions:
