services:
  redis:
    image: redis:7-alpine
    container_name: redis

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    networks:
      - traefik_proxy
      - default

    command: >
      redis-server
      --maxmemory ${REDIS_MAXMEMORY:-256mb}
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
      --tcp-backlog 511
      --timeout 300
      --tcp-keepalive 60
      --loglevel notice

    volumes:
      - $DATADIR/redis:/data

    environment:
      - TZ=$TZ

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

    labels:
      # Homepage Integration
      - "homepage.group=Backend"
      - "homepage.name=Redis"
      - "homepage.icon=redis.svg"
      - "homepage.description=In-Memory Data Store & Cache"
