services:
  # CrowdSec Bouncer - Traefik
  # NOTE: This uses the legacy fbonalair/traefik-crowdsec-bouncer image (last updated 2023)
  # For new deployments, consider using the Traefik CrowdSec Plugin instead:
  # https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin
  # The plugin supports AppSec features from CrowdSec 1.6.0+
  # Current image is kept for backward compatibility
  traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:0.5.0
    container_name: traefik-bouncer

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - traefik_proxy

    environment:
      GIN_MODE: release # default is debug (more logs)
      CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_TRAEFIK_BOUNCER_API_KEY # sudo docker exec crowdsec cscli bouncers add traefik-bouncer
      CROWDSEC_AGENT_HOST: crowdsec:8080 # CrowdSec host and port
      CROWDSEC_BOUNCER_LOG_LEVEL: 2 # https://pkg.go.dev/github.com/rs/zerolog#readme-leveled-logging

    labels:
      # Homepage Integration
      - "homepage.group=Middleware"
      - "homepage.name=Crowdsec Bouncer"
      - "homepage.description=Crowdsec Traefik Bouncer"

