services:
  # VSCode - VSCode Editing
  vscode:
    image: lscr.io/linuxserver/code-server:4.95.3
    container_name: vscode

    security_opt:
      - no-new-privileges=true

    restart: unless-stopped

    depends_on:
      traefik:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
          pids: 200
        reservations:
          cpus: "0.5"
          memory: 512M
          pids: 200

    networks:
      traefik_proxy:
        ipv4_address: $CODE_TRAEFIK_SUBNET_IP

    volumes:
      # Data directories
      - $DOCKERDIR:/data/jacker
      - $USERDIR:/data/home
      - $DATADIR/vscode/config:/config
      # Custom shell configuration
      - ./config/vscode/.bashrc:/config/.bashrc:ro
      # SECURITY: Host SSH keys removed - generate keys inside container for security
      # Git configuration for SSH operations
      - ~/.gitconfig:/config/.gitconfig:ro

    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DEFAULT_WORKSPACE: /data/jacker
      # SECURITY: GIT_SSH_COMMAND removed - use container-generated keys

    labels:
      - "traefik.enable=true"

      # HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=websecure"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$PUBLIC_FQDN`)"

      # TLS Configuration
      - "traefik.http.routers.vscode-rtr.tls=true"
      - "traefik.http.routers.vscode-rtr.tls.certresolver=http"
      - "traefik.http.routers.vscode-rtr.tls.options=tls-opts@file"

      # Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"

      # HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"

      # Homepage Integration
      - "homepage.group=Frontend Apps"
      - "homepage.name=VSCode"
      - "homepage.icon=vscode.svg"
      - "homepage.href=https://code.$PUBLIC_FQDN"
      - "homepage.description=Visual Studio Code Web Editor"
