services:
  # VSCode - VSCode Editing
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    depends_on:
      traefik:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      traefik_proxy:
        ipv4_address: $CODE_TRAEFIK_SUBNET_IP

    volumes:
      - $DOCKERDIR:/data/jacker
      - $USERDIR:/data/home
      - $DATADIR/vscode/config:/config

    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DEFAULT_WORKSPACE: /config/workspace

    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=websecure"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$PUBLIC_FQDN`)"
      - "traefik.http.routers.vscode-rtr.tls.certResolver=http"
      # Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"

      # Homepage Integration
      - "homepage.group=Frontend Apps"
      - "homepage.name=VSCode"
      - "homepage.icon=vscode.svg"
      - "homepage.href=https://code.$PUBLIC_FQDN"
      - "homepage.description=Visual Studio Code Web Editor"
