http:
  middlewares:
    # ====================================================================
    # STRICT CSP CHAINS
    # ====================================================================
    # Use for: APIs, static sites, modern SPAs with no inline scripts
    # Maximum security with no unsafe directives

    # OAuth-protected with strict CSP
    chain-oauth-strict:
      chain:
        middlewares:
          - crowdsec-bouncer@file         # CrowdSec IPS protection via Traefik plugin
          - middlewares-rate-limit-strict@file
          - secure-headers-strict         # STRICT CSP - No unsafe directives
          - middlewares-oauth@file
          - middlewares-cache-none@file
          - middlewares-compress@file

    # Public with strict CSP
    chain-public-strict:
      chain:
        middlewares:
          - middlewares-rate-limit@file
          - secure-headers-strict         # STRICT CSP - No unsafe directives
          - middlewares-cache-static@file
          - middlewares-compress@file

    # API with strict CSP
    chain-api-strict:
      chain:
        middlewares:
          - crowdsec-bouncer@file
          - middlewares-rate-limit-api@file
          - middlewares-cors-restrict@file
          - secure-headers-strict         # STRICT CSP - No unsafe directives
          - middlewares-cache-api@file
          - middlewares-compress@file
