http:
  middlewares:
    # Public chain for static content with caching
    chain-public-cached:
      chain:
        middlewares:
          - middlewares-rate-limit@file
          - middlewares-secure-headers@file
          - middlewares-cache-static@file
          - middlewares-compress@file

    # Public chain without authentication
    chain-public:
      chain:
        middlewares:
          - middlewares-rate-limit@file
          - middlewares-secure-headers@file
          - middlewares-cache-none@file
          - middlewares-compress@file
