http:
  middlewares:
    # Permissive CORS for public APIs
    middlewares-cors-allow:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Restrictive CORS for internal services
    # Note: Dynamic configuration doesn't support env variable expansion
    # Configure specific origins in service labels if needed
    middlewares-cors-restrict:
      headers:
        accessControlAllowOriginListRegex:
          - "^https://.*\\.jacarsystems\\.net$"  # Allow all Jacker subdomains
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlMaxAge: 100
        accessControlAllowCredentials: true
        addVaryHeader: true
