http:
  middlewares:
    middlewares-secure-headers:
      headers:
        # CORS Headers
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - HEAD
        accessControlAllowHeaders:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

        # Proxy Headers
        hostsProxyHeaders:
          - X-Forwarded-Host
        sslProxyHeaders:
          X-Forwarded-Proto: https

        # HSTS - 2 years with preload
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true

        # Security Headers
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: strict-origin-when-cross-origin

        # Content Security Policy - Strict but functional
        contentSecurityPolicy: |
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com;
          style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
          font-src 'self' data: https://fonts.gstatic.com;
          img-src 'self' data: blob: https:;
          connect-src 'self' wss: https:;
          media-src 'self';
          object-src 'none';
          frame-ancestors 'self';
          base-uri 'self';
          form-action 'self';
          upgrade-insecure-requests;

        # Permissions Policy - Restrict browser features
        permissionsPolicy: |
          accelerometer=(),
          camera=(),
          geolocation=(),
          gyroscope=(),
          magnetometer=(),
          microphone=(),
          payment=(),
          usb=(),
          interest-cohort=()

        # Custom Response Headers
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
          X-Frame-Options: SAMEORIGIN
          X-Content-Type-Options: nosniff
          X-XSS-Protection: "1; mode=block"
          X-Permitted-Cross-Domain-Policies: none
          X-Download-Options: noopen
          X-DNS-Prefetch-Control: off
          server: ""  # Hide server header
