http:
  middlewares:
    # CrowdSec Bouncer - Traefik Plugin
    # Official Plugin: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
    # Documentation: https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin
    # CRITICAL: Plugin name MUST match experimental.plugins declaration in traefik.yml
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:  # MUST match traefik.yml plugin name
          # Enable the bouncer plugin
          enabled: true

          # Logging level: DEBUG, INFO, WARN, ERROR
          logLevel: INFO

          # Operation mode: none, live, stream, alone, appsec
          # stream = recommended for production (periodic cache updates)
          # live = cached IP decisions (good for high traffic)
          # appsec = Application security mode with body inspection
          crowdsecMode: stream

          # Update interval for streaming mode (in seconds)
          updateIntervalSeconds: 60

          # CrowdSec LAPI connection
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: u3oW2DLwiUYmqGRwKBB9O9sJyNk+9Cd0MhpOeiYDSgU

          # Remediation: ban or captcha
          # ban = block malicious IPs
          # captcha = challenge with captcha (requires captcha provider)
          crowdsecAppsecEnabled: false
          crowdsecAppsecHost: crowdsec:7422

          # Forwarded headers (X-Forwarded-For support)
          forwardedHeadersCustomName: X-Forwarded-For

          # Client IP resolution
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16

          # Ban page customization (optional)
          # httpTimeoutSeconds: 10

          # Captcha configuration (if remediation is captcha)
          # captchaProvider: hcaptcha
          # captchaSiteKey: YOUR_SITE_KEY
          # captchaSecretKey: YOUR_SECRET_KEY
