http:
  middlewares:
    # Cache static content
    middlewares-cache-static:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000, immutable"  # 1 year for static assets

    # Cache for API responses
    middlewares-cache-api:
      headers:
        customResponseHeaders:
          Cache-Control: "private, max-age=60, must-revalidate"  # 1 minute for API responses

    # No cache for sensitive data
    middlewares-cache-none:
      headers:
        customResponseHeaders:
          Cache-Control: "no-store, no-cache, must-revalidate, proxy-revalidate"
          Pragma: no-cache
          Expires: "0"
