# Jacker Stack: {STACK_NAME}
################################################
#
# {Brief description of the stack}
# Documentation: {DOCS_URL}
#


# Networks
#========================================================================================================================
networks:
  default:
    driver: bridge
  traefik_proxy:
    external: true
  # Add custom networks as needed
  # custom_network:
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.100.0/24


# Volumes
#========================================================================================================================
# Define named volumes if needed
# volumes:
#   db_data:
#   config_data:


# Secrets
#========================================================================================================================
# Define secrets if needed
# secrets:
#   my_secret:
#     file: $SECRETSDIR/my_secret


# Services
#========================================================================================================================
include:
  - compose/{service1}.yml
  # - compose/{service2}.yml
  # - compose/{service3}.yml
