groups:
  - name: system_alerts
    interval: 30s
    rules:
      # CPU Usage Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% (current value: {{ $value }}%)"

      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage is above 95% (current value: {{ $value }}%)"

      # Memory Usage Alerts
      - alert: HighMemoryUsage
        expr: 100 * (1 - ((node_memory_MemAvailable_bytes) / (node_memory_MemTotal_bytes))) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% (current value: {{ $value }}%)"

      - alert: CriticalMemoryUsage
        expr: 100 * (1 - ((node_memory_MemAvailable_bytes) / (node_memory_MemTotal_bytes))) > 95
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 95% (current value: {{ $value }}%)"

      # Disk Usage Alerts
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 80% (current value: {{ $value }}%)"

      - alert: CriticalDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) > 90
        for: 2m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Critical disk usage detected"
          description: "Disk usage is above 90% (current value: {{ $value }}%)"

      # System Load Alerts
      - alert: HighSystemLoad
        expr: node_load15 / count(node_cpu_seconds_total{mode="idle"}) without (cpu, mode) > 2
        for: 10m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High system load detected"
          description: "System load is {{ $value }} (normalized by CPU count)"
