# Prometheus Data Source Configuration
apiVersion: 1

# List of datasources to delete from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# List of datasources to insert/update
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus-uid
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      # Prometheus type (Prometheus, Cortex, Mimir, Thanos)
      prometheusType: Prometheus
      prometheusVersion: 2.40.0

      # Query timeout
      timeout: 60

      # HTTP method (POST or GET)
      httpMethod: POST

      # Metric and label name lookup
      # Maximum number of metrics/labels that will be returned from the API
      metricLookupLimit: 10000

      # Incremental querying
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m

      # Disable metric/label lookup
      disableMetricsLookup: false

      # Custom query parameters
      customQueryParameters: ""

      # Recording rules
      recordingRulesEnabled: true

      # Exemplars
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger-uid

      # Caching
      cacheLevel: 'High'

      # Add CORS headers
      oauthPassThru: false

      # Alerting
      manageAlerts: true
      alertmanagerUid: alertmanager-uid