# Loki Data Source Configuration
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki-uid
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      # Maximum number of lines returned
      maxLines: 1000

      # Timeout for queries
      timeout: 60

      # Derived fields for trace correlation
      derivedFields:
        - datasourceUid: jaeger-uid
          matcherRegex: '"trace_id":"(\w+)"'
          name: traceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

        - datasourceUid: jaeger-uid
          matcherRegex: '"span_id":"(\w+)"'
          name: spanID
          url: '$${__value.raw}'

      # Alert configuration
      manageAlerts: false

      # Cache configuration
      cacheLevel: High

      # Service map
      serviceMap:
        datasourceUid: prometheus-uid
