apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus-uid
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      disableMetricsLookup: false
      cacheLevel: 'High'
      manageAlerts: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki-uid
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: prometheus-uid
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    uid: alertmanager-uid
    url: http://alertmanager:9093
    version: 1
    editable: true
    jsonData:
      implementation: prometheus
